apiVersion: v1
kind: Secret
metadata:
  name: clerk-secrets
type: Opaque
data:
  secret-key: ${CLERK_SECRET_KEY_BASE64}
  publishable-key: ${CLERK_PUBLISHABLE_KEY_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database-url: ${DATABASE_URL_BASE64}
  database-name: ${POSTGRES_DB_BASE64}
  username: ${POSTGRES_USER_BASE64}
  password: ${POSTGRES_PASSWORD_BASE64}
