version: "3.8"

services:
  api-gateway:
    env_file:
      - .env
    build:
      context: ../../services/api-gateway
      args:
        - NODE_ENV=production
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "4000:4000"
    depends_on:
      - transaction-service
      - reporting-service
      - notification-service
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
      - TRANSACTION_SERVICE_URL=http://transaction-service:5001
      - NOTIFICATION_SERVICE_URL=http://notification-service:5002
      - REPORTING_SERVICE_URL=http://reporting-service:5003
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  transaction-service:
    env_file:
      - .env
    build:
      context: ../../services/transaction-service
      args:
        - NODE_ENV=production
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  notification-service:
    env_file:
      - .env
    build:
      context: ../../services/notification-service
      args:
        - NODE_ENV=production
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  reporting-service:
    env_file:
      - .env
    build:
      context: ../../services/reporting-service
      args:
        - NODE_ENV=production
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-service:
    env_file:
      - .env
    build:
      context: ../../services/db-service
      args:
        - NODE_ENV=production
    restart: on-failure:3
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres-db:
    env_file:
      - .env
    image: postgres:17
    restart: on-failure:3
    volumes:
      - type: volume
        source: prod-payment-db-data
        target: /var/lib/postgresql/data
    networks:
      - instapay-net
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 2G
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PROD_POSTGRES_USER} -d ${PROD_POSTGRES_DB}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    env_file:
      - .env
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "3000:3000"
    networks:
      - instapay-net
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - API_GATEWAY_URL=http://api-gateway:4000
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  prod-payment-db-data:
    driver: local

networks:
  instapay-net:
    driver: bridge
