version: "3.8"

services:
  api-gateway:
    build:
      context: ../../services/api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - transaction-service
      - reporting-service
      - notification-service
    networks:
      - instapay-net
    environment:
      - TRANSACTION_SERVICE_URL=http://transaction-service:5001
      - NOTIFICATION_SERVICE_URL=http://notification-service:5002
      - REPORTING_SERVICE_URL=http://reporting-service:5003
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}

  transaction-service:
    build:
      context: ../../services/transaction-service
    networks:
      - instapay-net
    environment:
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payment_db
      - DB_USER=instapay
      - DB_PASSWORD=${PAYMENT_DB_PASSWORD}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
    depends_on:
      - payment-db

  notification-service:
    build:
      context: ../../services/notification-service
    networks:
      - instapay-net
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
    depends_on:
      - payment-db

  reporting-service:
    build:
      context: ../../services/reporting-service
    networks:
      - instapay-net
    environment:
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payment_db
      - DB_USER=instapay
      - DB_PASSWORD=${PAYMENT_DB_PASSWORD}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
    depends_on:
      - payment-db

  payment-db:
    build:
      context: ./payment-db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=instapay
      - POSTGRES_PASSWORD=${PAYMENT_DB_PASSWORD}
      # Change to "preserve" to keep data and run with sample data
      - INIT_MODE=reset
    volumes:
      - type: volume
        source: payment-db-data
        target: /var/lib/postgresql/data
    networks:
      - instapay-net

volumes:
  payment-db-data:
    driver: local

networks:
  instapay-net:
    driver: bridge
