apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    team: instapay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        team: instapay
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-gateway
          image: mini-instapay/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: ENABLE_METRICS
              value: "true"
            - name: TRANSACTION_SERVICE_URL
              value: "http://transaction-service:5001"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5002"
            - name: REPORTING_SERVICE_URL
              value: "http://reporting-service:5003"
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: CLERK_SECRET_KEY
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api-gateway
