apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
    team: instapay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        team: instapay
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9180"
    spec:
      containers:
        - name: notification-service
          image: mini-instapay/notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
            - containerPort: 9180
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database-url
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: CLERK_SECRET_KEY
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: SENDING_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: sending-email
            - name: GOOGLE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: google-email
            - name: GOOGLE_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: google-app-password
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
    - port: 9180
      targetPort: 9180
      protocol: TCP
      name: metrics
  selector:
    app: notification-service
