apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  labels:
    app: reporting-service
    team: instapay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
        team: instapay
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: reporting-service
          image: mini-instapay/reporting-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
              name: http
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: ENABLE_METRICS
              value: "true"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database-url
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: CLERK_SECRET_KEY
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secrets
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
spec:
  type: ClusterIP
  ports:
    - port: 5003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: reporting-service
